name: expenses_repository
description: The repositories for expenses xd
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencias:
  flutter: 
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  fl_charts: ^0.66.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

flutter:
  uses-material-design: true
dependencies:
  cloud_firestore: ^5.0.0
